;; ----------------------------
;; |  PROJECT EULER exercise  |
;; ----------------------------

#|
44. Pentagon numbers

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
|#

(defun is-pent (x)
    (= 5 (mod (sqrt (+ 1 (* 24 x))) 6))
)

(defun D ()
    (loop for j from 1 to 5000 do
        (setq Pj (/ (* j (- (* 3 j) 1)) 2))
        (loop for k from (+ j 1) to 5000 do
            (setq Pk (/ (* k (- (* 3 k) 1)) 2))
            
            (cond 
                ((logand (is-pent (- Pk Pj)) (is-pent (+ Pk Pj))) (return-from D (- Pk Pj)))
                (t ())
            )
        )
    )
)
